name: CI

on:
  push:
    branches: [ master ]
    tags:
      - '*.*.*'
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/checkout@v2
        name: Get OBS headers
        with:
          repository: obsproject/obs-studio
          ref: 26.1.1
          fetch-depth: 1
          persist-credentials: false
          path: deps\obs-source
      - name: Setup Python
        uses: actions/setup-python@v2.2.1
      - name: Install Python requirements
        run: python -m pip install pymsbuild Cython
      - name: Run a build
        run: python build.py
        env:
          OBS_SOURCE: ${{ github.workspace }}\deps\obs-source
      - name: List output
        run: dir -Recurse out
      - name: Publish package
        uses: actions/upload-artifact@v2
        with:
          name: win64
          path: out/python

      - name: Upload to release
        if: ${{ success() && startsWith(github.ref, 'refs/tags/') }}
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ github.token }}
          file: obs-python-*.zip
          file_glob: true
          tag: ${{ github.ref }}
          overwrite: true
