name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2.2.1
      - name: Run a test build
        run: python build.py
      - name: List output
        run: dir -Recurse out
      - name: Publish package
        uses: actions/upload-artifact@v2
        with:
          name: win64
          path: out/python
